version: 0.2
phases:
  install:
    commands:
      - npm install -g yarn
      - npm install -g serverless
  pre_build:
    commands:
      - echo Yarn install...
      - yarn install
  build:
    commands:
      - echo serverless deploy...
      - serverless deploy